"""add filename

Revision ID: b034a37d1152
Revises: cd04d4864075
Create Date: 2022-08-28 17:58:07.027960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b034a37d1152'
down_revision = 'cd04d4864075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint', sa.Column('filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaint', 'filename')
    # ### end Alembic commands ###
