"""Initial migration.

Revision ID: cd04d4864075
Revises: 
Create Date: 2022-08-20 22:14:36.834580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd04d4864075'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_info', sa.Column('tg_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_info', 'tg_chat_id')
    # ### end Alembic commands ###
